services:
  api:
    container_name: apianimal
    image: pedrcavalc/animal-api:1.1
    restart: always
    ports:
      - "3000:8000"
  front:
    container_name: front-animal
    image: pedrcavalc/animal-front:1.1
    restart: always
    ports:
    - "3001:3000"
networks:
  default:
    driver: custom-driver-1